### ISSUE TITLE
Error: FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by ChiakiYukine** [LmeSzinc/StarRailCopilot#277]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

在安装时进度卡在80%，显示“系统找不到指定的文件”，无法安装。

### 相关 Logs

```Text
./toolkit/Lib/site-packages/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/pip/_vendor/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/uiautomator2/init.py minicap_urls no need to patch
./toolkit/Lib/site-packages/uiautomator2/init.py appdir already patched
./toolkit/Lib/site-packages/adbutils/mixin.py not exist
Process: [ 0% ]
==================== SHOW DEPLOY CONFIG ====================
Repository: cn
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Language: zh-CN
Rest of the configs are the same as default
Process: [ 10% ]
+---------------------------------------------------+
|                    UPDATE ALAS                    |
+---------------------------------------------------+
[CurrentCommit] 0c2b748f65fdefec4e96149e97e090a7f583f3ee
Fetch url: https://vip.123pan.cn/1815343254/pack/LmeSzinc_StarRailCopilot_master/latest.json
[LatestCommit] 0c2b748f65fdefec4e96149e97e090a7f583f3ee
Already up to date
Execute: ['G:/game/assistant/StarRailTool/StarRailCopilot/toolkit/Git/mingw64/bin/git.exe', 'reset', '--hard', 'origin/master']
+----------------------------------------------------------+
|                    KILL EXISTING ALAS                    |
+----------------------------------------------------------+
List process
Found 245 processes
Process: [ 60% ]
+-----------------------------------------------------------+
|                    UPDATE DEPENDENCIES                    |
+-----------------------------------------------------------+
All dependencies installed
Process: [ 70% ]
+--------------------------------------------------+
|                    UPDATE APP                    |
+--------------------------------------------------+
+---------------------------------------------------------+
|                    START ADB SERVICE                    |
+---------------------------------------------------------+
==================== REPLACE ADB ====================
G:/MuMuPlayer-12.0/shell/adb.exe is same as G:/game/assistant/StarRailTool/StarRailCopilot/toolkit/Lib/site-packages/adbutils/binaries/adb.exe, skip
No need to replace
Process: [ 80% ]
Traceback (most recent call last):
  File "G:\game\assistant\StarRailTool\StarRailCopilot\installer.py", line 55, in <module>
    run_install()
  File "G:\game\assistant\StarRailTool\StarRailCopilot\installer.py", line 15, in run_install
    run()
  File "G:\game\assistant\StarRailTool\StarRailCopilot\deploy\installer.py", line 31, in run
    installer.install()
  File "G:\game\assistant\StarRailTool\StarRailCopilot\deploy\installer.py", line 21, in install
    self.adb_install()
  File "G:\game\assistant\StarRailTool\StarRailCopilot\deploy\Windows\adb.py", line 29, in adb_install
    self.brute_force_connect()
  File "G:\game\assistant\StarRailTool\StarRailCopilot\deploy\Windows\emulator.py", line 67, in brute_force_connect
    devices = self.adb_devices()
  File "G:\game\assistant\StarRailTool\StarRailCopilot\deploy\Windows\emulator.py", line 49, in adb_devices
    result = self.subprocess_execute([self.adb, 'devices'])
  File "G:\game\assistant\StarRailTool\StarRailCopilot\deploy\Windows\config.py", line 207, in subprocess_execute
==================== ADB CONNECT ====================
-------------------- ADB DEIVCES --------------------
G:/game/assistant/StarRailTool/StarRailCopilot/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)
  File "G:\game\assistant\StarRailTool\StarRailCopilot\toolkit\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "G:\game\assistant\StarRailTool\StarRailCopilot\toolkit\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Error: FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

**Comment by LmeSzinc** [comment]
检查 `./toolkit/Lib/site-packages/adbutils/binaries/adb.exe` 文件是否存在

**Comment by ChiakiYukine** [comment]
> 检查 `./toolkit/Lib/site-packages/adbutils/binaries/adb.exe` 文件是否存在

检查了一下，文件存在，但仍然提示找不到文件……
![Uploading Cache_-17f8181bcf5c26f4.jpg…]()

**Comment by ChiakiYukine** [comment]
> 检查 `./toolkit/Lib/site-packages/adbutils/binaries/adb.exe` 文件是否存在
检查之后是存在的，但不知道为什么SRC安装的时候还是显示找不到指定的文件。
[main_2024-01-17.log](https://github.com/LmeSzinc/StarRailCopilot/files/13980049/main_2024-01-17.log)

**Comment by ChiakiYukine** [comment]
> 检查 `./toolkit/Lib/site-packages/adbutils/binaries/adb.exe` 文件是否存在

检察之后是存在的，但SRC仍然报错找不到指定文件……
[2024-01-19_webapp.txt](https://github.com/LmeSzinc/StarRailCopilot/files/13980060/2024-01-19_webapp.txt)
![binaries目录下截图](https://github.com/LmeSzinc/StarRailCopilot/assets/62099356/a7432232-ddc7-41af-b04e-1246eecee56c)

**Comment by wpae0528** [comment]
之前用的好好的，今天打开报了一样的错误

**Comment by wpae0528** [comment]
无语了，查了半天感觉是win11升级完之后 注册表的位置变了？升级的补丁是Windows 11, version 23H2    升级完之后 只在这个位置下面能找到exe后缀的路径   \Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store

**Comment by ChiakiYukine** [comment]
我试着在另一台笔记本上安装了一下，可以正常运行，但是直接把文件夹复制到这台电脑上就显示找不到指定文件，我不知道我的电脑出什么问题了……

**Comment by ChiakiYukine** [comment]
很神奇，安装gpt-sovits的时候报了类似的错，解决之后SRC这边的问题居然歪打正着地解决了（
gpt-sovits安装的时候是.bat文件显示找不到文件，以管理员的身份运行cmd，输入：setx ComSpec %SystemRoot%\system32\cmd.exe /m， 之后就找到了。然后试了试SRC的安装，之前找不到文件的错误就解决了。
所以找不到文件可能是权限问题之类的，供参考（
