### ISSUE TITLE
安装错误 FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:/MuMu9/emulator/nemu9'

### ISSUE THREAD

**Issue by yige-yigeren** [LmeSzinc/StarRailCopilot#88]
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/53390868/0cef13b7-dd19-4b35-8131-f35466e81e17)
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/53390868/5cd86267-b6af-4310-a2f2-ed588282cc2b)
    for emulator in self.all_emulators:
  File "E:\StarRailCopilot\module\device\platform\utils.py", line 24, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "E:\StarRailCopilot\module\device\platform\emulator_windows.py", line 471, in all_emulators
    for file in iter_folder(abspath(os.path.dirname(uninstall)), ext='.exe'):
  File "E:\StarRailCopilot\module\device\platform\utils.py", line 38, in iter_folder
    for file in os.listdir(folder):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:/MuMu9/emulator/nemu9'
版本是0.51
OS：
版本        Windows 11 专业版
版本        22H2
安装日期      2022/11/10
操作系统版本    22621.2134
体验        Windows 功能体验包 1000.22659.1000.0

**Comment by yige-yigeren** [comment]
控制台信息：（没有安装mumu9）
StarRailCopilot
./toolkit/Lib/site-packages/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/pip/_vendor/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/uiautomator2/init.py minicap_urls no need to patch
./toolkit/Lib/site-packages/uiautomator2/init.py appdir already patched
./toolkit/Lib/site-packages/adbutils/mixin.py not exist
Process: [ 0% ]
==================== SHOW DEPLOY CONFIG ====================
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Language: zh-CN
Theme: dark
Rest of the configs are the same as default
Process: [ 10% ]
+---------------------------------------------------+
|                    UPDATE ALAS                    |
+---------------------------------------------------+
==================== GIT INIT ====================
"E:/StarRailCopilot/toolkit/Git/mingw64/bin/git.exe" init
Reinitialized existing Git repository in E:/StarRailCopilot/.git/
[ success ]
Process: [ 12% ]
==================== SET GIT PROXY ====================
Git config http.proxy = None
Git config https.proxy = None
Git config http.sslVerify = true
Process: [ 13% ]
==================== SET GIT REPOSITORY ====================
Git config remote "origin".url = https://github.com/LmeSzinc/StarRailCopilot
Process: [ 15% ]
==================== FETCH REPOSITORY BRANCH ====================
"E:/StarRailCopilot/toolkit/Git/mingw64/bin/git.exe" fetch origin master
[ success ]
Process: [ 40% ]
==================== PULL REPOSITORY BRANCH ====================
"E:/StarRailCopilot/toolkit/Git/mingw64/bin/git.exe" reset --hard origin/master
HEAD is now at 50f49a6 Merge pull request #86 from LmeSzinc/dev
[ success ]
Process: [ 45% ]
"E:/StarRailCopilot/toolkit/Git/mingw64/bin/git.exe" checkout master
[ success ]
Process: [ 48% ]
==================== SHOW VERSION ====================
"E:/StarRailCopilot/toolkit/Git/mingw64/bin/git.exe" --no-pager log --no-merges -1
commit b734e1c40753586c9c957405729d6e6fb45d126f
Author: LmeSzinc <37934724+LmeSzinc@users.noreply.github.com>
Date:   Mon Sep 11 23:49:07 2023 +0800

    Fix: Template name at config add
[ success ]
Process: [ 50% ]
+----------------------------------------------------------+
|                    KILL EXISTING ALAS                    |
+----------------------------------------------------------+
List process
Found 291 processes
Process: [ 60% ]
+-----------------------------------------------------------+
|                    UPDATE DEPENDENCIES                    |
+-----------------------------------------------------------+
All dependencies installed
Process: [ 70% ]
+--------------------------------------------------+
|                    UPDATE APP                    |
+--------------------------------------------------+
+---------------------------------------------------------+
|                    START ADB SERVICE                    |
+---------------------------------------------------------+
==================== REPLACE ADB ====================
From https://github.com/LmeSzinc/StarRailCopilot
 * branch            master     -> FETCH_HEAD
Already on 'master'
Traceback (most recent call last):
  File "E:\StarRailCopilot\installer.py", line 55, in <module>
    run_install()
  File "E:\StarRailCopilot\installer.py", line 15, in run_install
    run()
  File "E:\StarRailCopilot\deploy\installer.py", line 31, in run
    installer.install()
  File "E:\StarRailCopilot\deploy\installer.py", line 21, in install
    self.adb_install()
  File "E:\StarRailCopilot\deploy\Windows\adb.py", line 25, in adb_install
    self.adb_replace()
  File "E:\StarRailCopilot\deploy\Windows\emulator.py", line 134, in adb_replace
    replace = list(self.iter_adb_to_replace())
  File "E:\StarRailCopilot\deploy\Windows\emulator.py", line 122, in iter_adb_to_replace
    for adb in self.emulator_manager.all_adb_binaries:
  File "E:\StarRailCopilot\module\device\platform\utils.py", line 24, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "E:\StarRailCopilot\module\device\platform\emulator_base.py", line 243, in all_adb_binaries
    for emulator in self.all_emulators:
  File "E:\StarRailCopilot\module\device\platform\utils.py", line 24, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "E:\StarRailCopilot\module\device\platform\emulator_windows.py", line 471, in all_emulators
    for file in iter_folder(abspath(os.path.dirname(uninstall)), ext='.exe'):
  File "E:\StarRailCopilot\module\device\platform\utils.py", line 38, in iter_folder
    for file in os.listdir(folder):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:/MuMu9/emulator/nemu9'
Error: From https://github.com/LmeSzinc/StarRailCopilot
 * branch            master     -> FETCH_HEAD
Already on 'master'
Traceback (most recent call last):
  File "E:\StarRailCopilot\installer.py", line 55, in <module>
    run_install()
  File "E:\StarRailCopilot\installer.py", line 15, in run_install
    run()
  File "E:\StarRailCopilot\deploy\installer.py", line 31, in run
    installer.install()
  File "E:\StarRailCopilot\deploy\installer.py", line 21, in install
    self.adb_install()
  File "E:\StarRailCopilot\deploy\Windows\adb.py", line 25, in adb_install
    self.adb_replace()
  File "E:\StarRailCopilot\deploy\Windows\emulator.py", line 134, in adb_replace
    replace = list(self.iter_adb_to_replace())
  File "E:\StarRailCopilot\deploy\Windows\emulator.py", line 122, in iter_adb_to_replace
    for adb in self.emulator_manager.all_adb_binaries:
  File "E:\StarRailCopilot\module\device\platform\utils.py", line 24, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "E:\StarRailCopilot\module\device\platform\emulator_base.py", line 243, in all_adb_binaries
    for emulator in self.all_emulators:
  File "E:\StarRailCopilot\module\device\platform\utils.py", line 24, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "E:\StarRailCopilot\module\device\platform\emulator_windows.py", line 471, in all_emulators
    for file in iter_folder(abspath(os.path.dirname(uninstall)), ext='.exe'):
  File "E:\StarRailCopilot\module\device\platform\utils.py", line 38, in iter_folder
    for file in os.listdir(folder):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:/MuMu9/emulator/nemu9'
70%

**Comment by yige-yigeren** [comment]
下载渠道是国际（我在外网），弹窗后卡70%

**Comment by yige-yigeren** [comment]
已解决
